# true -> work with pbs on metacentrum
# false -> run locally, no pbs
# if run by run_all*, it is set automatically
run_on_metacentrum: True
metacentrum:
  chunks: 1
  ncpus_per_chunk: 1  # max 20 cpus per node(chunk)
  walltime: "20:00:00"  # 18:00:00
  memory: 4gb
  queue: charon
  name: bukov_sens_3D
  workspace_rel: ../../workspace
  swrap: /storage/liberec3-tul/home/pavel_exner/workspace/swrap/src/swrap

n_samples: 512 # must be power of 2 due to salib
n_processes: 440
#n_samples: 2 # must be power of 2 due to salib
#n_processes: 4
# 32 x 31186
sample_shape: [32, 31186]

collect_only: False
mesh_only: False
make_plots: False
# if True, it removes sample dir right after the sample is collected
clean_sample_dir: True

second_order_sa: True
parameters:
#  - name: storativity
#    type: lognorm
#    bounds: [-14.5662279378421, 2.0]
  - name: young_modulus
    type: lognorm
    bounds: [24.8176103991685, 0.5]
  - name: init_stress_x
    type: lognorm
    bounds: [ 17.5531801762476, 0.3]
  - name: init_stress_y
    type: lognorm
    bounds: [ 16.7599495371307, 0.3]
  - name: init_stress_z
    type: lognorm
    bounds: [ 16.4545678875795, 0.3]
  - name: perm_k0
    type: lognorm
    bounds: [ -44.9530895712128, 2.0]
#  - name: perm_kr
#    type: lognorm
#    bounds: [ -43.7491167668869, 0.5]
  - name: perm_eps
    type: truncnorm
    bounds : [1.1, 1000, 33, 9]
  - name: perm_delta
    type: lognorm
    bounds: [ -36.8413614879047, 0.1]
  - name: perm_gamma
    type: lognorm
    bounds: [ 1.79175946922806, 0.1]
  - name: conductivity_a
    type: unif
    bounds: [ -1, 1 ]
  - name: conductivity_b
    type: unif
    bounds: [ -1, 1 ]
  - name: conductivity_c
    type: unif
    bounds: [ -1, 1 ]

# FULL time axis
start_time: &start_time 0
end_time: &end_time 130
#bored_time: &bored_time 107
output_times: &output_times
  - {'begin': 0, 'step': 100, 'end': 100}
  - {'begin': 100, 'step': 1, 'end': 112}
  - {'begin': 112, 'step': 1, 'end': *end_time}

  #- {begin: *start_time, step: 0.1, end: *bored_time}
  #- {begin: *bored_time, step: 1, end: 100}
  #- {begin: *bored_time, step: 1, end: *end_time}

geometry:
  # base of the mesh file name
  mesh_name: Bukov_both_h100_31k
#  # depth of the center of the box and of the coordinate system
#  # x,y,z dimension
#  box_dimensions: [100, 100]
#  # tunnel center
#  tunnel_center: [0, 0, 0]
#  tunnel_dimX: &tunnel_dimX 4.375 # X cross-section
#  tunnel_dimY: &tunnel_dimY 3.5 # Y cross-section
#  tunnel_mesh_step: 0.25 # 0.0625 # 0.25 # 0.125 # 0.5
#  max_elem_size: 10 # 5 # 10 # 3.7

# parameters substituted into the HM model template
hm_params:
    mesh: tunnel_mesh.msh # healed mesh is used at the end (programmatically replaced)
    in_file: D02_hm

    output_times: *output_times
    start_time: *start_time
    end_time: *end_time
#    bored_time: *bored_time

#    tunnel_dimX: *tunnel_dimX
#    tunnel_dimY: *tunnel_dimY

# physical parameters of main interest:
    biot_coefficient: 0.2
    # porosity nu=0.007, beta_w=4e-10 Pa-1, beta_s = (biot-nu)*(1-biot)/bulk_modulus
    storativity: 2.998917e-07  # S = rho * g * (beta_s + nu * beta_w)
    # permeability k=6e-22 m2, dyn. viscosity mu=0.001 Pa.s, g=9.81 m.s-2
    bulk_conductivity: 5.886E-15  # K = k * rho * g /mu
    init_pressure: 20 # 3MPa = p = h*rho*g => h = 300 m

    young_modulus: 60e9
    poisson_ratio: 0.23
    init_stress_x: 42e6
    init_stress_y: 19e6
    init_stress_z: 14e6

    # non-linear permeability
#    perm_kr: 8e-20
#    perm_km: 8e-17
#    perm_beta: 4e-7
#    perm_gamma: 3e-7
    perm_k0: 8e-20
    perm_kr: 8e-17
    perm_eps: 33.3
    perm_delta: 4e-7
    perm_gamma: 3e-7

    conductivity_a: 0
    conductivity_b: 0
    conductivity_c: 0

# solver's settings
    mechanics_solver__a_tol: 0
    mechanics_solver__r_tol: 1e-12
    mechanics_solver__options: -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg #-ksp_monitor
        # -ksp_type cg -pc_type icc -pc_factor_levels 2 -ksp_diagonal_scale -ksp_diagonal_scale_fix -pc_factor_fill 3.0 -ksp_monitor

    flow_solver__a_tol: 0
    flow_solver__r_tol: 1e-12

    flow_solver__options: -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg #-ksp_monitor
        # -ksp_type cg -pc_type hypre -pc_hypre_type boomeramg  -pc_hypre_boomeramg_coarsen_type HMIS -pc_hypre_boomeramg_strong_threshold 0.5  -ksp_monitor

copy_files: []
  #- C01_hm_tmpl.yaml

# The flow executable and arguments to use.
local:
  flow_executable:
    ### this is the simplest case when using inside docker (or singularity) image
    # running with empty environment (env -i); keep flow123d paths:
    - LD_LIBRARY_PATH=/opt/flow123d/lib
    - /opt/flow123d/bin/flow123d
    ### this is for installed Flow123d package or individual build
#    - /home/domesova/flow123d_3.1.0/bin/fterm.sh
#    - /home/paulie/local/flow123d/flow123d_3.1.0/bin/fterm.sh
#    - /home/paulie/Workspace/flow123d/bin/fterm
    ### for flow123d individual build (not docker image install)
#    - --no-term
#    - rel
    ### for flow123d (docker image install)
#    - --version
#    - "3.1.0"
#    - --tty
#    - "false"
#    - --interactive
#    - "false"
    ### this is for both installed Flow123d package or individual build
#    - run
    - --no_profiler
  np: 1
  gmsh_executable:
    - /home/paulie/Workspace/Endorse-2Dtest-Bayes/venv/bin/gmsh